# Generated by Django 4.0.3 on 2022-04-06 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='latest update time')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='delete tag')),
                ('title', models.CharField(max_length=64, null=True, verbose_name='title')),
                ('content', models.TextField(null=True, verbose_name='content')),
                ('is_draft', models.BooleanField(default=True, verbose_name='draft tag')),
                ('creator_id', models.IntegerField(verbose_name='creator id')),
                ('publish_at', models.DateTimeField(null=True, verbose_name='publish time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoticeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='latest update time')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='delete tag')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('desc', models.CharField(max_length=256, verbose_name='description')),
            ],
            options={
                'db_table': 'notice_type',
            },
        ),
        migrations.CreateModel(
            name='ReceiverType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='latest update time')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='delete tag')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('desc', models.CharField(max_length=256, verbose_name='description')),
            ],
            options={
                'db_table': 'notice_receiver_type',
            },
        ),
        migrations.CreateModel(
            name='ReceiverTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='latest update time')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='delete tag')),
                ('receiver_id', models.IntegerField(verbose_name='receiver')),
                ('read_at', models.DateTimeField(verbose_name='read time')),
                ('noticestore', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notice.noticestore', verbose_name='notice')),
            ],
            options={
                'db_table': 'notice_receiver_tag',
            },
        ),
        migrations.AddField(
            model_name='noticestore',
            name='notice_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.noticetype', verbose_name='notice type'),
        ),
        migrations.AddField(
            model_name='noticestore',
            name='receiver_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.receivertype', verbose_name='receiver type'),
        ),
    ]
