# Generated by Django 4.0.3 on 2022-05-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0007_remove_privatenotice_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backlog',
            name='redirect_url',
        ),
        migrations.RemoveField(
            model_name='backlog',
            name='title',
        ),
        migrations.RemoveField(
            model_name='privatenotice',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='privatenotice',
            name='is_node_done',
        ),
        migrations.RemoveField(
            model_name='privatenotice',
            name='node',
        ),
        migrations.RemoveField(
            model_name='privatenotice',
            name='obj_key',
        ),
        migrations.AddField(
            model_name='backlog',
            name='handler',
            field=models.CharField(max_length=64, null=True, verbose_name='handler'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='initiator',
            field=models.CharField(max_length=64, null=True, verbose_name='initiator'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='read status'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='obj_key',
            field=models.CharField(max_length=64, null=True, verbose_name='obj key'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='obj_name',
            field=models.CharField(max_length=64, null=True, verbose_name='obj name'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='obj_status',
            field=models.CharField(max_length=64, null=True, verbose_name='obj status'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='read_at',
            field=models.DateTimeField(null=True, verbose_name='read time'),
        ),
        migrations.AddField(
            model_name='privatenotice',
            name='content',
            field=models.TextField(null=True, verbose_name='content'),
        ),
    ]
